### ISSUE TITLE
AnimatedCursor cannot load config file on Linux systems; crashes.

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/AnimatedCursor#3]
**Bug Name:** AnimatedCursor cannot load config file on Linux systems; crashes.
**Issue ID:** #3
**Version Number:** AnimatedCrosshair v1.0
**Minecraft Version Number:** 1.8.9 w/ Forge (FML)
**Forge Version Number:** 11.15.1.2318-1.8.9
**Reported By:** Snuggle
**Reported On:** 2018-02-24
**Environment:** Linux, probably other POSIX systems like MacOS, BSD etc.
**Neofetch:**
![image](https://user-images.githubusercontent.com/26250962/36626514-089ad558-192c-11e8-8036-f96e80fd912b.png)

**Description:**
Cursor is stuck looking "default" upon joining a server/logging into Minecraft. Doing `/crosshair` crashes Minecraft.

I believe it's checking for a config file, that it can't find, and then isn't quite sure what to render afterwards and thus throws a render exception of some kind.

**Screenshot after loading world:**
![image](https://user-images.githubusercontent.com/26250962/36626501-e2682746-192b-11e8-96b4-76a6905f9888.png)

**Stacktrace:**
```co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: java.io.FileNotFoundException: There is no properties file for this crosshair!
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.config.ConfigUtil.getProperties(ConfigUtil.java:120)
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.gui.ConfigGui.resetProperties(ConfigGui.java:209)
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.gui.ConfigGui.<init>(ConfigGui.java:57)
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.command.CommandCrosshair.lambda$processCommand$0(CommandCrosshair.java:35)
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.TickDelay.run(TickDelay.java:50)
co.bugg.animatedcrosshair.gui.ConfigGui:resetProperties:216]: 	at co.bugg.animatedcrosshair.TickDelay.onTick(TickDelay.java:42)
```

```
java.lang.NullPointerException: Rendering screen
	at co.bugg.animatedcrosshair.AnimatedCrosshair.drawCrosshair(AnimatedCrosshair.java:244)
	at co.bugg.animatedcrosshair.gui.ConfigGui.func_73863_a(ConfigGui.java:76)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
```

**Full crashlog:**
https://pastebin.com/xcbte28a

**Steps To Reproduce:**
1) Use a Linux system
2) Open Minecraft
3) Join a server/local world
4) Type `/crosshair`
5) Enjoy a creeper blowing up your entire Minecraft :crying_cat_face:

_This bug can be reproduced with no other modifications present._

**Comment by Palomarrrr** [comment]
will this ever be fixed? i just found this mod and it looks really useful

**Comment by robere2** [comment]
> will this ever be fixed? i just found this mod and it looks really useful

Most likely not by me, but I'd encourage any other developer to fork this repository, fix this, and improve the mod in other ways. I can't reasonably see myself contributing to this project again any time in the near future, so I am archiving this repository. Apologies!
